temporal:
  # Connection configuration
  hostPort: "localhost:7233"  # Local Temporal server
  namespace: "default"
  environment: "local"        # "local" or "remote"
  defaultTaskQueue: "account-transfer-queue"  # Default task queue for workflows

  # Connection options
  timeout: "5s"
  retryOptions:
    initialInterval: "100ms"
    maximumInterval: "10s"
    maximumAttempts: 5
    backoffCoefficient: 2.0

workflows:
  AccountTransferWorkflow:
    purpose: "Transfers money between accounts with validation and notification."
    workflowIDRecipe: "transfer_{{.from_account}}_{{.to_account}}_{{.amount}}"
    input:
      type: "TransferInput"
      fields:
        - from_account: "Source account ID"
        - to_account: "Destination account ID"
        - amount: "Amount to transfer"
    output:
      type: "TransferOutput"
      description: "Transfer confirmation with charge ID"
    taskQueue: "account-transfer-queue"
    activities:
      - name: "validate"
        timeout: "5s"
      - name: "withdraw"
        timeout: "5s"
      - name: "deposit"
        timeout: "5s"
      - name: "sendNotification"
        timeout: "5s"
      - name: "undoWithdraw"
        timeout: "5s"

  AccountTransferWorkflowScenarios:
    purpose: "Extended account transfer workflow with approval and error handling scenarios."
    workflowIDRecipe: "transfer_scenario_{{.scenario_type}}_{{.from_account}}_{{.to_account}}"
    input:
      type: "TransferInput"
      fields:
        - from_account: "Source account ID"
        - to_account: "Destination account ID"
        - amount: "Amount to transfer"
    output:
      type: "TransferOutput"
      description: "Transfer confirmation with charge ID"
    taskQueue: "account-transfer-queue"
    scenarios:
      - name: "AccountTransferWorkflowRecoverableFailure"
        description: "Simulates a recoverable failure scenario"
      - name: "AccountTransferWorkflowHumanInLoop"
        description: "Requires human approval before proceeding"
        approvalTimeout: "30s"
      - name: "AccountTransferWorkflowAdvancedVisibility"
        description: "Includes advanced visibility features"
    activities:
      - name: "validate"
        timeout: "5s"
      - name: "withdraw"
        timeout: "5s"
      - name: "deposit"
        timeout: "5s"
      - name: "sendNotification"
        timeout: "5s"
      - name: "undoWithdraw"
        timeout: "5s"
